#
# Makefile
#
# Makefile for Poco Foundation
#

include $(PROJECT_BASE)/build/rules/global

objects = message rtdconfig rtdevent rtdvalue

target         = rtdprotocol
target_version = $(LIBVERSION)
target_libs    =

include $(PROJECT_BASE)/build/rules/lib
