# config.make generated by configure script
PROJECT_CONFIG = Linux
PROJECT_BASE = /home/rangh/Documents/WorkSpace/SourceCode/rtdCollector
PROJECT_BUILD = /home/rangh/Documents/WorkSpace/SourceCode/rtdCollector
PROJECT_FLAGS = 
PROJECT_PREFIX = ./
export PROJECT_CONFIG
export PROJECT_BASE
export PROJECT_BUILD
export PROJECT_FLAGS
export PROJECT_PREFIX
