#
# Makefile
#
# Makefile for Poco Foundation
#

include $(PROJECT_BASE)/build/rules/global

objects = ascii atomicCounter bugCheck channel configurable debugger environment errorHandler essage event exception fPEnvironment memoryStream mutex \
	namedEvent numberFormatter numericString process refCountedObject runnable signalHandler string syslogChannel \
	thread threadLocal timespan timestamp 

target         = util
target_version = $(LIBVERSION)
target_libs    =

include $(PROJECT_BASE)/build/rules/lib
