#
# Makefile
#
# Makefile for Poco Foundation
#

include $(PROJECT_BASE)/build/rules/global

objects = main

target         = dbusWrapperRecv
target_version = $(LIBVERSION)
target_libs    = dbuswrapper util

include $(PROJECT_BASE)/build/rules/exec
