#
# Makefile
#
# Makefile for Poco Foundation
#

include $(PROJECT_BASE)/build/rules/global

objects = main

target         = rtdTest
target_version = $(LIBVERSION)
target_libs    = rtdcollector tinyxml2 util

include $(PROJECT_BASE)/build/rules/exec
