#
# Makefile
#
# Makefile for Poco Foundation
#

include $(PROJECT_BASE)/build/rules/global

objects = tinyxml2 

target         = tinyxml2
target_version = $(LIBVERSION)
target_libs    =

include $(PROJECT_BASE)/build/rules/lib
